name: Metrics

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: jawQ
          template: classic
          base: header, activity, community, repositories
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          output_action: commit
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: main
          filename: github-metrics.svg
          config_timezone: Asia/Shanghai
